name: Reminder

on: 
  schedule:
    - cron: '57 * * * *'

jobs:
  birthday-reminder:
  
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
    
      - name: Run reminder script
        run: |
          bash birthday_reminder.sh
